openapi: 3.2.0
info:
  title: Secret Manager Onboarding API
  description: 'This API can be used to resolve secrets from references and returns its actual confidential value.

    '
  version: 0.0.1
  contact:
    name: TARDIS
    email: tadis@nop.telekom.de
    url: https://developer.telekom.de/
  license:
    name: Apache 2.0
  x-api-category: TARDIS
servers:
- url: https://locahost:8080
  description: For local development
tags:
- name: onboarding
paths:
  /v1/onboarding/environments/{envId}:
    put:
      operationId: upsertEnvironment
      summary: Create or update an environment
      description: Create or update an environment that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/EnvironmentWriteRequest'
      responses:
        '200':
          $ref: '#/components/responses/OnboardingResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    delete:
      operationId: deleteEnvironment
      summary: Delete an environment
      description: Delete an environment that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v1/onboarding/environments/{envId}/teams/{teamId}:
    put:
      operationId: upsertTeam
      summary: Create or update a team
      description: Create or update a team that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        description: The id or reference to a team
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/TeamWriteRequest'
      responses:
        '200':
          $ref: '#/components/responses/OnboardingResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    delete:
      operationId: deleteTeam
      summary: Delete a team
      description: Delete a team that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        description: The id or reference to a team
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /v1/onboarding/environments/{envId}/teams/{teamId}/apps/{appId}:
    put:
      operationId: upsertApp
      summary: Create or update an app
      description: Create or update an app that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        description: The id or reference to a team
        required: true
        schema:
          type: string
      - name: appId
        in: path
        description: The id or reference to an app
        required: true
        schema:
          type: string
      requestBody:
        $ref: '#/components/requestBodies/ApplicationWriteRequest'
      responses:
        '200':
          $ref: '#/components/responses/OnboardingResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    delete:
      operationId: deleteApp
      summary: Delete an app
      description: Delete an app that is identified by its reference in the request body
      tags:
      - onboarding
      parameters:
      - name: envId
        in: path
        description: The id or reference to an environment
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        description: The id or reference to a team
        required: true
        schema:
          type: string
      - name: appId
        in: path
        description: The id or reference to an app
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  responses:
    ErrorResponse:
      description: In case of any error, this object is returned
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ApiProblem'
    OnboardingResponse:
      description: Successful retrieval of secrets
      content:
        application/json:
          schema:
            type: object
            required:
            - items
            properties:
              items:
                type: array
                description: A list of available secret references
                minItems: 0
                maxItems: 10
                items:
                  $ref: '#/components/schemas/ListSecretItem'
    NoContent:
      description: Successful operation with no content
  schemas:
    ApplicationWriteRequest:
      type: object
      required:
      - secrets
      properties:
        strategy:
          $ref: '#/components/schemas/WriteStrategy'
        secrets:
          type: array
          description: A list of secrets to be created or updated for the application
          minItems: 0
          maxItems: 10
          items:
            $ref: '#/components/schemas/NamedSecret'
    ApiProblem:
      description: Based on https://www.rfc-editor.org/rfc/rfc9457.html
      type: object
      required:
      - type
      - status
      - title
      - detail
      properties:
        type:
          type: string
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    NamedSecret:
      type: object
      required:
      - name
      - value
      properties:
        name:
          type: string
          description: The name of the secret
        value:
          type: string
          description: The value of the secret
    EnvironmentWriteRequest:
      type: object
      required:
      - secrets
      properties:
        strategy:
          $ref: '#/components/schemas/WriteStrategy'
        secrets:
          type: array
          description: A list of secrets to be created or updated for the environment
          minItems: 0
          maxItems: 10
          items:
            $ref: '#/components/schemas/NamedSecret'
    WriteStrategy:
      type: string
      enum:
      - merge
      - replace
      default: replace
      description: 'The strategy defines how the provided secrets should be applied.

        With "merge", the provided secrets will be merged with the existing secrets. With "replace",

        the provided secrets will replace the existing secrets.

        If not provided, "replace" will be used as default strategy.

        '
    SecretRef:
      description: A reference to a secret
      type: string
    ListSecretItem:
      type: object
      required:
      - name
      - id
      properties:
        name:
          type: string
          description: The name of the secret
        id:
          $ref: '#/components/schemas/SecretRef'
    TeamWriteRequest:
      type: object
      required:
      - secrets
      properties:
        strategy:
          $ref: '#/components/schemas/WriteStrategy'
        secrets:
          type: array
          description: A list of secrets to be created or updated for the team
          minItems: 0
          maxItems: 10
          items:
            $ref: '#/components/schemas/NamedSecret'
  requestBodies:
    EnvironmentWriteRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnvironmentWriteRequest'
    ApplicationWriteRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationWriteRequest'
    TeamWriteRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TeamWriteRequest'
