openapi: 3.2.0
info:
  title: Keycloak Admin REST Client Registration Policy API
  description: This is a REST API reference for the Keycloak Admin
  version: '1'
security:
- access_token: []
tags:
- name: Client Registration Policy
paths:
  /{realm}/client-registration-policy/providers:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Client Registration Policy
      summary: Base path for retrieve providers with the configProperties properly filled
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentTypeRepresentation'
components:
  schemas:
    ComponentTypeRepresentation:
      type: object
      properties:
        helpText:
          type: string
        id:
          type: string
        metadata:
          type: object
          additionalProperties: true
        properties:
          type: array
          items:
            $ref: '#/components/schemas/ConfigPropertyRepresentation'
    ConfigPropertyRepresentation:
      type: object
      properties:
        defaultValue:
          type: object
        helpText:
          type: string
        label:
          type: string
        name:
          type: string
        options:
          type: array
          items:
            type: string
        secret:
          type: boolean
        type:
          type: string
  securitySchemes:
    access_token:
      type: http
      scheme: bearer
      bearerFormat: null
externalDocs:
  description: Schema source code
  url: https://github.com/keycloak/keycloak/tree/6.0.1/core/src/main/java/org/keycloak/representations
