openapi: 3.2.0
info:
  title: Keycloak Admin REST Scope Mappings API
  description: This is a REST API reference for the Keycloak Admin
  version: '1'
security:
- access_token: []
tags:
- name: Scope Mappings
paths:
  /{realm}/client-scopes/{id}/scope-mappings:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get all scope mappings for the client
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingsRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappings
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/clients/{client}:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get the roles associated with a client’s scope Returns roles for the client
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
    post:
      tags:
      - Scope Mappings
      summary: Add client-level roles to the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: postByRealmClientScopesByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
    delete:
      tags:
      - Scope Mappings
      summary: Remove client-level roles from the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: deleteByRealmClientScopesByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/clients/{client}/available:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: The available client-level roles Returns the roles for the client that can be…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsClientsByClientAvailable
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/clients/{client}/composite:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get effective client roles Returns the roles for the client that are associated…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsClientsByClientComposite
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/realm:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get realm-level roles associated with the client’s scope
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsRealm
      x-operation-id-source: derived
    post:
      tags:
      - Scope Mappings
      summary: Add a set of realm-level roles to the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: postByRealmClientScopesByIdScopeMappingsRealm
      x-operation-id-source: derived
    delete:
      tags:
      - Scope Mappings
      summary: Remove a set of realm-level roles from the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: deleteByRealmClientScopesByIdScopeMappingsRealm
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/realm/available:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get realm-level roles that are available to attach to this client’s scope
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsRealmAvailable
      x-operation-id-source: derived
  /{realm}/client-scopes/{id}/scope-mappings/realm/composite:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client scope (not name)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get effective realm-level roles associated with the client’s scope What this…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientScopesByIdScopeMappingsRealmComposite
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get all scope mappings for the client
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingsRepresentation'
      operationId: getByRealmClientsByIdScopeMappings
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/clients/{client}:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get the roles associated with a client’s scope Returns roles for the client
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
    post:
      tags:
      - Scope Mappings
      summary: Add client-level roles to the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: postByRealmClientsByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
    delete:
      tags:
      - Scope Mappings
      summary: Remove client-level roles from the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: deleteByRealmClientsByIdScopeMappingsClientsByClient
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/clients/{client}/available:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: The available client-level roles Returns the roles for the client that can be…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsClientsByClientAvailable
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/clients/{client}/composite:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: client
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get effective client roles Returns the roles for the client that are associated…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsClientsByClientComposite
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/realm:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get realm-level roles associated with the client’s scope
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsRealm
      x-operation-id-source: derived
    post:
      tags:
      - Scope Mappings
      summary: Add a set of realm-level roles to the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: postByRealmClientsByIdScopeMappingsRealm
      x-operation-id-source: derived
    delete:
      tags:
      - Scope Mappings
      summary: Remove a set of realm-level roles from the client’s scope
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RoleRepresentation'
        required: true
      responses:
        2XX:
          description: success
      operationId: deleteByRealmClientsByIdScopeMappingsRealm
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/realm/available:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get realm-level roles that are available to attach to this client’s scope
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsRealmAvailable
      x-operation-id-source: derived
  /{realm}/clients/{id}/scope-mappings/realm/composite:
    parameters:
    - in: path
      name: realm
      description: realm name (not id!)
      required: true
      schema:
        type: string
      style: simple
    - in: path
      name: id
      description: id of client (not client-id)
      required: true
      schema:
        type: string
      style: simple
    get:
      tags:
      - Scope Mappings
      summary: Get effective realm-level roles associated with the client’s scope What this…
      responses:
        2XX:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleRepresentation'
      operationId: getByRealmClientsByIdScopeMappingsRealmComposite
      x-operation-id-source: derived
components:
  schemas:
    RoleRepresentation:
      type: object
      properties:
        attributes:
          type: object
          additionalProperties: true
        clientRole:
          type: boolean
        composite:
          type: boolean
        composites:
          $ref: '#/components/schemas/RoleRepresentation-Composites'
        containerId:
          type: string
        description:
          type: string
        id:
          type: string
        name:
          type: string
    RoleRepresentation-Composites:
      type: object
      properties:
        client:
          type: object
          additionalProperties: true
        realm:
          type: array
          items:
            type: string
    MappingsRepresentation:
      type: object
      properties:
        clientMappings:
          type: object
          additionalProperties: true
        realmMappings:
          type: array
          items:
            $ref: '#/components/schemas/RoleRepresentation'
  securitySchemes:
    access_token:
      type: http
      scheme: bearer
      bearerFormat: null
externalDocs:
  description: Schema source code
  url: https://github.com/keycloak/keycloak/tree/6.0.1/core/src/main/java/org/keycloak/representations
