openapi: 3.2.0
info:
  title: File manager Deleting API
  description: A simple file manager for uploading and downloading files.
  version: 0.0.1
  contact:
    name: TARDIS
    email: tardis@nop.telekom.de
    url: https://developer.telekom.de/
  license:
    name: Apache 2.0
  x-api-category: TARDIS
servers:
- url: https://locahost:8080
  description: For local development
security:
- bearerAuth: []
tags:
- name: deleting
paths:
  /v1/files/{fileId}:
    delete:
      operationId: deleteFile
      summary: Delete a file
      description: Deletes a file from the server with the specified Id. The id should follow the convention.
      tags:
      - deleting
      parameters:
      - name: fileId
        in: path
        description: Id of the file, should follow the convention <env>--<group>--<team>--<fileName>
        required: true
        schema:
          type: string
      security:
      - bearerAuth: []
      responses:
        '204':
          description: File deleted
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  responses:
    ErrorResponse:
      description: In case of any error, this object is returned
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ApiProblem'
  schemas:
    ApiProblem:
      description: Based on https://www.rfc-editor.org/rfc/rfc9457.html
      type: object
      required:
      - type
      - status
      - title
      - detail
      properties:
        type:
          type: string
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication
